### PR TITLE
completed the spec

### PR DESCRIPTION
**Pull request by erichulburd**
Hi Charles,

I've made a lot of changes to cover the GB spec more comprehensively, but used your basic Rule framework to do so.  The tests show the level of coverage.

I'll eventually need to make a few changes for slight modifications on the standard that SDGE has made.

Also packaged it as a gem (though haven't pushed it to a repo).

Let me know what you think, if you have questions,

Eric

### CODE REVIEW

**Comment by erichulburd** [comment]
Also, I've parsed the LocalTimeParameters but haven't had the energy to adjust any of the dates returned from the parser. Currenty everything just returns unadjusted UTC.

**Comment by cew821** [comment]
Eric: this is great work. Thanks so much for contributing. I'll try to complete this merge in the next day or two. 

I was discussing parsing strategies with some other folks, and they raised some performance concerns with our approach (mainly related to how many times we search the DOM to assemble the Ruby objects). But I think it makes sense to try to get the DSL to those objects solid (via your `gb_classes` module), and then we can work on optimizing the parser logic to build those objects when/if needed.

Thanks again!

**Comment by erichulburd** [comment]
Yeah, I wasn't sure whether Nokogiri was storing the xpath or the actual xml in the `@entry_xml`, but in an effort to just get a functioning interface I just initiated pretty much everything during the initial parse. It might be a couple of weeks before I can start to think about optimization.

Also, I hadn't thought too deeply about it, but thought a configuration file might be appropriate since some utilities are going to differ slightly in their implementation. I'm working with SDGE right now, but I may just start an alternative branch in my repo until something clicks.

**Comment by cew821** [comment]
I have accepted these changes. I'm going to work cleaning up some of the tests. I am opening a separate issue to discuss the potential need for utility-specific configuration files. I would like to better understand what specific differences you're seeing across green button implementations. Thanks again for the work here!

**Pull request merged**
